language: go

os:
  - linux
  - osx

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - ./tests/functional-test.sh

